# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20171020_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='permanent',
            field=models.BooleanField(default=False, help_text='By default this entry will use a temporary (302) redirect. Check this to make it permanent (301).'),
        ),
    ]
