# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 10:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20171107_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='webm',
        ),
    ]
