# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20180801_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='focal_x',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='focal_y',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
