# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-06 14:08
from __future__ import unicode_literals

import cms.apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20190523_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=250, storage=cms.apps.media.models.MediaStorage(), upload_to='uploads/files'),
        ),
    ]
