# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20200406_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
