# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_page_cached_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='A unique portion of the URL that is used to identify this specific page using human-readable keywords (e.g., about-us)'),
        ),
    ]
