# Generated by Django 2.2.16 on 2020-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200812_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='A unique portion of the URL that is used to identify this specific page using human-readable keywords (e.g., about-us)', max_length=150),
        ),
    ]
