# Generated by Django 2.2.9 on 2020-10-06 10:12

import cms.apps.pages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200916_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=cms.apps.pages.models.PageForeignKey(blank=True, limit_choices_to={'is_content_object': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='pages.Page'),
        ),
    ]
