# Generated by Django 2.2.9 on 2020-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201007_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_content_object',
        ),
    ]
