# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2021-01-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201009_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='default',
            field=models.NullBooleanField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='left',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='right',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
