# Generated by Django 2.2.9 on 2020-11-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20201102_1250'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='page',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('version_for_id__isnull', False), ('left__isnull', True), ('right__isnull', True)), ('version_for_id__isnull', True), _connector='OR'), name='versions_not_in_page_tree'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner_id__isnull', False), ('left__isnull', True), ('right__isnull', True)), ('owner_id__isnull', True), _connector='OR'), name='translations_not_in_page_tree'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('version_for_id__isnull', True), ('owner_id__isnull', True), ('left__isnull', False), ('right__isnull', False)), ('version_for_id__isnull', False), ('owner_id__isnull', False), _connector='OR'), name='page_mptt_values'),
        ),
    ]
